version: '3.8'

services:
  sshManager:
    image: ghcr.io/kokofixcomputers/temporarysshsessionmanager:main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mounting the Docker socket
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock  # Optional, usually not needed
